# -*- coding: utf-8 -*-
"""Build the localization supplement from hand translations + existing TSV.

For every English residual dumped from the live tree this composes a zhCN
translation (hand base + parenthesized suffix, regex families, or squashed-id
lookup) and emits @display: alias lines.  The output is merged into
OfficialDependencyNames.tsv between idempotent BEGIN/END markers so the CASC
regeneration can simply re-run this script afterwards.
"""
import re
import sys

sys.path.insert(0, r"e:\Code\sc2\Work\sc2ed_dpifix\tools")
from hand_translations import HAND, SS, SUFFIX

ROOT = r"e:\Code\sc2\Work\sc2ed_dpifix"
TSV = rf"{ROOT}\packages\hook\OfficialDependencyNames.tsv"
RESIDUAL = rf"{ROOT}\tools\residual_en.txt"
OUT_SUPPLEMENT = rf"{ROOT}\tools\supplement_display.tsv"
OUT_UNCOVERED = rf"{ROOT}\tools\supplement_uncovered.txt"
MARK_BEGIN = "# === supplement begin (generated by tools/build_supplement.py) ==="
MARK_END = "# === supplement end ==="

# Composite key mirror of the hook's CanonicalDisplayKey: lowercase, parens/
# brackets/braces to space, collapse whitespace, strip.
def canonical(text):
    text = text.lower()
    text = re.sub(r"[()\[\]{}]", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def squash(text):
    return canonical(text).replace(" ", "")

def norm(text):
    """Internal-whitespace normalization only (for HAND key lookups)."""
    return re.sub(r"\s+", " ", text.strip())

WEDGES = re.compile(r"^TerrainObjectXelNagaWedges(\d+x\d+)_(\d+)_(\d+)$")
KNOCKBACK = re.compile(r"^Unit Knockback By(\d+) (.+)$")
KNOCKBACK_TAIL = {
    "Apply Behavior": "-施加行为",
    "Impact": "-撞击",
    "Place Holder Launch Missile": "-占位发射导弹",
    "Place Holder Launch MissileHLM": "-占位发射导弹HLM",
    "Remove Behavior": "-移除行为",
}

def translate_base(base):
    """Translate the suffix-free base of a residual; None if unknown."""
    b = norm(base)
    if b in HAND:
        return HAND[b]
    if b.startswith("Shooter - ") and norm(b[len("Shooter - "):]) in SS:
        return "射手-" + SS[norm(b[len("Shooter - "):])]
    m = WEDGES.match(b)
    if m:
        return f"萨尔纳加楔形地形{m.group(1)}_{m.group(2)}_{m.group(3)}"
    m = KNOCKBACK.match(b)
    if m and m.group(2) in KNOCKBACK_TAIL:
        return f"单位击退{m.group(1)}{KNOCKBACK_TAIL[m.group(2)]}"
    return None

def suffix_zh(s):
    """Translate one parenthesized suffix; None if unknown."""
    s = s.strip()
    low = s.lower()
    if low in SUFFIX:
        return SUFFIX[low]
    if re.fullmatch(r"[\d.]+", s):  # bare numbers pass through
        return s
    if s.startswith("CEffect"):  # engine class names stay as-is
        return "-" + s
    return None

def translate(text, ids):
    """Return zh translation for one residual line, or None."""
    # 1. split trailing parenthesized suffix chain and compose
    m = re.match(r"^(.*?)\s*((?:\([^()]*\)\s*)+)$", text)
    if m:
        base, tail = m.group(1), re.findall(r"\(([^()]*)\)", m.group(2))
        zh_tail = [suffix_zh(s) for s in tail]
        if all(zh_tail):
            joined = "".join(zh_tail)
            if not base.strip():  # pure suffix strings: "(Unused)"
                return "(" + joined.lstrip("-") + ")"
            zh_base = translate_base(base)
            if zh_base is not None:
                return zh_base + joined
            squashed = ids.get(squash(base))
            if squashed:
                return squashed + joined
    # 2. hand table covers the exact whole string (incl. mid-string parens)
    whole = translate_base(text)
    if whole is not None:
        return whole
    # 3. full-string squashed id lookup (hook does the same at runtime)
    return ids.get(squash(text))

def main():
    ids = {}
    with open(TSV, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or "\t" not in line:
                continue
            key, _, value = line.rstrip("\n").partition("\t")
            if not key.startswith("@"):
                ids[key.strip().lower()] = value

    with open(RESIDUAL, encoding="utf-8") as fh:
        residuals = [line.rstrip("\n") for line in fh if line.strip()]

    entries = {}
    uncovered = []
    unknown_suffixes = set()
    for text in residuals:
        m = re.match(r"^(.*?)\s*((?:\([^()]*\)\s*)+)$", text)
        if m:
            for s in re.findall(r"\(([^()]*)\)", m.group(2)):
                if suffix_zh(s) is None:
                    unknown_suffixes.add(s.strip())
        zh = translate(text, ids)
        if zh:
            entries[canonical(text)] = zh
        else:
            uncovered.append(text)

    with open(OUT_SUPPLEMENT, "w", encoding="utf-8") as fh:
        for key in sorted(entries):
            fh.write(f"@display:{key}\t{entries[key]}\n")
    with open(OUT_UNCOVERED, "w", encoding="utf-8") as fh:
        fh.write("\n".join(uncovered) + "\n")

    # idempotent merge: replace previous supplement section, append new
    with open(TSV, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    out, in_section = [], False
    for line in lines:
        if line == MARK_BEGIN:
            in_section = True
            continue
        if line == MARK_END:
            in_section = False
            continue
        if not in_section:
            out.append(line)
    out.append(MARK_BEGIN)
    out.extend(f"@display:{k}\t{entries[k]}" for k in sorted(entries))
    out.append(MARK_END)
    with open(TSV, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")

    print(f"residuals={len(residuals)} covered={len(entries)} "
          f"uncovered={len(uncovered)}")
    if unknown_suffixes:
        print("unknown suffixes:", sorted(unknown_suffixes))
    if uncovered:
        print("uncovered samples:")
        for s in uncovered[:30]:
            print(f"  {s}")

if __name__ == "__main__":
    main()
